# Generated by Django 5.2 on 2025-04-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_area_of_specialization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='calendly_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
