# Generated by Django 5.1.6 on 2025-02-19 09:32

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_forum_moderator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='reply',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
