# Generated by Django 5.2 on 2025-04-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_alter_post_content_alter_reply_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='context',
            field=models.CharField(blank=True, choices=[('citation', 'Citation'), ('proposal', 'Proposal Writing'), ('ai', 'Use of AI'), ('plagiarism', 'Plagiarism')], max_length=20, null=True),
        ),
    ]
