# Generated by Django 5.1.4 on 2024-12-31 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='annotated_file',
            field=models.FileField(blank=True, null=True, upload_to='workspace_annotations/'),
        ),
    ]
